### ISSUE TITLE
Problem with aggregation

### ISSUE THREAD

**Issue by felipe-augusto** [craftup/node-mongo-tenant#14]
Hello there, we are experiencing some problems using aggregate with node-mongo-tenant, your implementation of the aggregate is changing the way we need to call the `aggregate` function. The standart Mongoose way is:

```js
Model.aggregate([{ $match: something }])
````

But the way you implemented the aggregate, we need to remove the brackets:

```js
Model.aggregate({ $match: something })
````

I dont't know if this is the intended behavior, but if is not, a quick fix is possible: instead of slicing the arguments, you just need to get the pipeline passed to aggregate and unshift it to add the `$match` on the tenantIdKey.

```js
  static aggregate(pipeline) {
    
    if (this.hasTenantContext) {
      pipeline.unshift({
        $match: {
          [tenantIdKey]: this[tenantIdGetter]()
        }
      })
    }

    return super.aggregate.apply(this, pipeline);
  }
```

**Comment by alrik** [comment]
Thanks for the detailed bug report @felipe-augusto . I'll dig into it and provide a fix asap.

**Comment by alrik** [comment]
`Mongoose.Model.aggregate` supports both, aggregation pipeline operator objects or an operators array. Proper handling of array operations, as described above, has been implemented with #15.
It would be awesome to get a quick review from you @felipe-augusto.

**Comment by felipe-augusto** [comment]
God, I totally forgot about this. Thank you very much for the fix! I will update my version tomorrow.

**Comment by alrik** [comment]
No problem :) In case you there is any issue left with aggregate, simply open another issue and reference this one.
