### ISSUE TITLE
Using the custom config "tenantIdKey" for create

### ISSUE THREAD

**Issue by osvathrobi** [craftup/node-mongo-tenant#33]
I would like to use the `tenantIdKey` value automatically when I create new objects instead of hard coding it. I am using custom `tenantIdKey` field specified as a config value.

Instead of:
```
  Cup.create({...body, 'tenantId': user.id})
    .then((cup) => cup.view(true))
    .then(success(res, 201))
    .catch(next)
```

I think it would be nice to just specify it in a similar manner to update, delete, query where it fills in the proper key:
```
  Cup.byTenantId(user.id).create(body)
    .then((cup) => cup.view(true))
    .then(success(res, 201))
    .catch(next)
```
And it could automatically fill in the tenantId field. Not sure if this is useful or not, maybe this is a bad idea?

**Comment by alrik** [comment]
Yes, that should be possible. I'm going to check this.

**Comment by alrik** [comment]
Hey @osvathrobi,

i wrote a test case for your scenario and it seems to work.
How did you configure the custom `tenantIdKey`?
**Note**: currently the configuration of mongo-tenant is on a per applied schema basis.

Feel free to reopen the issue, if the problem persists.
