### ISSUE TITLE
Problem with discriminator key

### ISSUE THREAD

**Issue by felipe-augusto** [craftup/node-mongo-tenant#38]
Hello, I'm trying to use mongo-tenant with [mongoose discriminators](http://mongoosejs.com/docs/discriminators.html). But I'm having a problem in this piece of the code:

```js
// inherit all static properties from the mongoose base model
    for (let staticProperty of Object.getOwnPropertyNames(BaseModel)) {
      if (MongoTenantModel.hasOwnProperty(staticProperty)
      || ['arguments', 'caller'].indexOf(staticProperty) !== -1
      ) {
        continue;
      }

      MongoTenantModel[staticProperty] = BaseModel[staticProperty];
    }

    return MongoTenantModel;
```

This throws the following error:

```
TypeError: Cannot assign to read only property 'baseModelName' of function 'class MongoTenantModel extends BaseModel
```

The problem is that the discriminator sets a property `baseModelName` that has the following descriptor:

```js
{ 
  value: 'baseModelName',
  writable: false,
  enumerable: false,
  configurable: true
}
```

And since is not settable, it throws an error.

**Comment by alrik** [comment]
Thanks @felipe-augusto for reporting and fixing :heart: 

I'm going to release this until tomorrow.
