### ISSUE TITLE
mongoose 'deleteOne' function is still able to delete across tenants

### ISSUE THREAD

**Issue by himbaer** [craftup/node-mongo-tenant#41]
Hey,

unforunately I'm still able to delete documents across tenants via mongoose's [deleteOne](https://mongoosejs.com/docs/api.html#query_Query-deleteOne) function.

Could you please have a look?
Cheers 👍

**Comment by himbaer** [comment]
I will also create a branch with a test-case so you can easily reproduce

**Comment by alrik** [comment]
@himbaer thanks for your report. We'll have a look at it asap.
