### ISSUE TITLE
TypeError: Class constructor MongoTenantModel cannot be invoked without 'new' since mongoose@4.8.1

### ISSUE THREAD

**Issue by alrik** [craftup/node-mongo-tenant#5]
see Automattic/mongoose#4947

**Comment by alrik** [comment]
@benhjames until it's clarified whether its a mongoose regression bug or an api change, mongo-tenant has to live with, I'll pin the mongoose peer dependency to 4.7.x

**Comment by bensalilijames** [comment]
Great, cheers.

**Comment by alrik** [comment]
I released version 1.0.3. For now mongo-tenant is compatible with `mongoose >=4.3.0, <=4.7.x`.

**Comment by bensalilijames** [comment]
I believe this is fixed now in mongoose 4.8.3!

**Comment by alrik** [comment]
@benhjames I'll publish a new version tomorrow.
