### ISSUE TITLE
Multitenant model does not override updateMany. 

### ISSUE THREAD

**Issue by RsknCankov** [craftup/node-mongo-tenant#60]
Hi there,

I am using .byTenant followed by updateMany in order to execute batch update. Problem is tenant model actually ignores clientId field and execute update on documents regardless tenantId field.

**Comment by RsknCankov** [comment]
I made a PR #61  regarding this issue, please review and let me know if something needs to be changed.

**Comment by alrik** [comment]
@RsknCankov Thanks for your contribution. Your fix just landed in 1.8.0 release. :tada:
